export {
  createOneBotWebQQService,
} from '../webqq/adapters/onebot/service'

export type {
  OneBotWebQQOptions,
  OneBotRobotProfile,
  OneBotRobotState,
  WebQQChatType,
  WebQQContacts,
  WebQQForwardItem,
  WebQQFriend,
  WebQQFriendCategory,
  WebQQGroup,
  WebQQGroupAnnouncement,
  WebQQGroupInfo,
  WebQQGroupInfoQuery,
  WebQQGroupMember,
  WebQQLiveMessage,
  WebQQMessage,
  WebQQMessageElement,
  WebQQMessageQuery,
  WebQQMessageReaction,
  WebQQMessageReactionUser,
  WebQQNotice,
  WebQQNoticeAction,
  WebQQProtocol,
  WebQQRecallPayload,
  WebQQRecordTranscriptionQuery,
  WebQQRecentContact,
} from './types'
